# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-08-24 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='用户名字'),
        ),
    ]
